name: Generate PDF Versions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  generate_puppeteer_pdf:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev wget
          npm install puppeteer
      - name: Generate PDF with Puppeteer
        run: |
          node -e "
            const puppeteer = require('puppeteer');
            (async () => {
              try {
                const browser = await puppeteer.launch({
                  args: ['--no-sandbox', '--disable-setuid-sandbox']
                });
                const page = await browser.newPage();
                await page.goto('file://${{ github.workspace }}/dist/index.html', { 
                  waitUntil: 'networkidle0',
                  timeout: 30000
                });
                await page.pdf({ 
                  path: 'resume-puppeteer.pdf',
                  format: 'A4',
                  printBackground: true,
                  margin: { top: '20mm', right: '20mm', bottom: '20mm', left: '20mm' }
                });
                await browser.close();
                console.log('PDF generated successfully');
              } catch (error) {
                console.error('Error generating PDF:', error);
                process.exit(1);
              }
            })();
          "
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add resume-puppeteer.pdf"
          file_pattern: "resume-puppeteer.pdf"

  generate_wkhtmltopdf_pdf:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Generate PDF with wkhtmltopdf
        uses: docker://alpine/wkhtmltopdf
        with:
          args: --enable-local-file-access ${{ github.workspace }}/dist/index.html resume-wkhtmltopdf.pdf
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add resume-wkhtmltopdf.pdf"
          file_pattern: "resume-wkhtmltopdf.pdf"
